Pipfile, Pipfile.lock, Procfile, config/settings.py
update database and add heroku to settings
=> update database, add heroku to settings

game/serializers.py, game/urls.py, game/views.py
feat:adds endpoint for users times, adds slug field for username
=> feat:adds endpoint for users times, adds slug field for username

README.md
=> fix: removed code from readme.md

README.md, game/views.py
Initial entry into the README file, a table of endpoints that are currently available for users & times, along with the included djoser endpoints
=> Initial readme

static/css/game.css, static/js/game.js, templates/game/game.html
Make game centered and scaled to fit screen
=> feat: make game centered and scaled to fit screen

static/js/game.js
adds ability to turn background music on and off with the M button
=> feat: adds ability to turn background music on and off

tests.md
Add tests for character & game behavior
=> test: add initial gameplay tests

static/assets/levels/level-1.json, static/assets/levels/level-2.json, static/assets/levels/level-3.json, static/js/game.js
add ice physics to level 2/custom player accel to level.json format
=> Ice Physics

static/js/game.js
adds level number to HUD in top left corner-no styling
=> feat: adds level number to HUD in top left corner-no styling

static/js/components/gameplay.js, static/js/game.js, static/js/index.js
Pass user token to Phaser using postMessage
=> Iframe api

templates/game/game.html
I mean it's like, just some site someone else controls. Who knows what they might send to our users, really?
=> fix: add SRI hash to Phaser script

static/js/level.js
unpolished code for next level button
=> Restart next buttons

config/settings.py
adds pagination to the BE for 10
=> feat: adds pagination to the BE for 10

static/js/App.js
Fix the userToken not being available in the game
=> fix: re-add userToken stashing

game/urls.py, static/js/components/gameplay.js
Move game off root URL and replace it with Homepage
=> refactor: move game off root URL

static/js/components/leaderboard.js, templates/game/homepage.html
fix: convert times to time string
=> fix: convert times to time string

static/js/level.js, static/js/utils.js
Prevent game from crashing when player takes certain actions in or near the OOB area
=> Oob crash fix

static/js/App.js, static/js/components/navbar.js, static/js/components/usertimeslink.js, static/js/consts.js, templates/game/game.html, templates/game/homepage.html
Dynamically create leaderboard links based on number of levels
=> Dynamic leaderboards

static/css/game.css
Update the game container aspect ratio to match the game itself
=> Aspect ratio update

static/js/components/gameplay.js, static/js/index.js, static/js/level.js
Redirect the user to the homepage when they exit the game
=> feat: redirect to homepage when user exits the game

README.md
Feat: Update control and game story in readme.
=> updated controls to readme.md

static/js/App.js, static/js/components/navbar.js, static/js/components/usertimeslink.js
Reduce leaderboards and add full game links
=> fix: reduce number of leaderboards shown by one

README.md, game/urls.py, game/views.py
adds endpoint for full run times by logged in user
user/full-run-times/
=> feat: adds endpoint for full run times of logged in user

static/css/title.css, static/js/App.js, static/js/components/fullgameleaderboard.js, static/js/components/gameplay.js, static/js/components/leaderboard.js, static/js/components/login-or-showuser.js, static/js/components/login.js, static/js/components/navbar.js, static/js/components/register.js, static/js/components/title.js, static/js/components/userfullgameleaderboard.js, static/js/components/usertimes.js, static/js/components/usertimeslink.js
Co-authored-by: Alexis <leximainw@gmail.com>
=> feat: navbar updated along with other formatting issues

static/js/components/fullgameleaderboard.js, static/js/level.js
Fix global full game leaderboard and allow player to press N after completing a level to progress to the next level
=> Leaderboard final fixes

static/js/App.js, static/js/components/login.js, static/js/components/register.js, static/js/game.js
Add a reroute from the login page to the homepage, tidy up code
=> Login to homepage
